
export enum PageType {
  DASHBOARD = 'DASHBOARD',
  DOCUMENT = 'DOCUMENT',
  DATABASE = 'DATABASE',
  CALENDAR = 'CALENDAR',
  ANALYTICS = 'ANALYTICS',
  KANBAN = 'KANBAN',
  LEGAL_DEMANDS = 'LEGAL_DEMANDS',
  OUTREACH_DASHBOARD = 'OUTREACH_DASHBOARD',
  PROSPECT_DB = 'PROSPECT_DB',
  FUNNEL = 'FUNNEL',
  TEMPLATES = 'TEMPLATES',
  RESOURCE_GRID = 'RESOURCE_GRID',
  INVOICE_GENERATOR = 'INVOICE_GENERATOR',
  FINANCE_DASHBOARD = 'FINANCE_DASHBOARD',
  SETTINGS = 'SETTINGS',
  CLIENT_PORTAL = 'CLIENT_PORTAL',
  INTEGRATIONS = 'INTEGRATIONS',
  CONTENT_PLANNER = 'CONTENT_PLANNER',
  ENVIRONMENT = 'ENVIRONMENT'
}

export interface NavItem {
  id: string;
  label: string;
  icon?: string;
  type: PageType;
  children?: NavItem[];
  description?: string;
}

export interface UploadedFile {
  id: string;
  name: string;
  size: number;
  type: string;
  uploadDate: string;
  cardId?: string;
  clientId?: string;
  folderPath?: string;
  data?: string; // Base64 string of the file content
  linkUrl?: string; // For external links (Drive/Dropbox)
}

export interface ClientFolder {
  id: string;
  clientId: string;
  name: string;
  path: string; // e.g., "03_Monthly Content/November 2025"
}

export interface PageContent {
  id: string;
  text: string;
  files: UploadedFile[];
}

export interface Client {
  id: string;
  name: string;
  status: 'Active' | 'Onboarding' | 'Churned' | 'Lead';
  revenue: number;
  nextShoot: string;
  contact: string;
  package?: string;
  driveUrl?: string; // Link to Google Drive Folder
  packageAssignments?: ClientPackageAssignment[];
}

export interface DashboardMetric {
  label: string;
  value: string;
  trend: number;
  color: 'pink' | 'teal' | 'lime';
}

export interface KanbanItem {
  id: string;
  title: string;
  client: string;
  status: string;
  tag?: string;
  dueDate?: string;
}

export interface KanbanColumn {
  id: string;
  title: string;
  date?: string;
}

export interface CalendarEvent {
  id: string;
  title: string;
  date: string;
  type: 'shoot' | 'post' | 'meeting' | 'outreach' | 'followup';
  client: string;
  packageId?: string;
  packageTaskId?: string;
  autoGenerated?: boolean;
}

export interface PackageTaskTemplate {
  id: string;
  title: string;
  type: CalendarEvent['type'];
  offsetDays: number;
}

export interface PackageDefinition {
  id: string;
  name: string;
  description?: string;
  price?: number;
  tasks: PackageTaskTemplate[];
}

export interface ClientPackageAssignment {
  id: string;
  packageId: string;
  startDate: string;
  calendarEventIds: string[];
}

export interface Prospect {
  id: string;
  company: string;
  contactName: string;
  industry: string;
  platform: 'LinkedIn' | 'Instagram' | 'Email';
  status: 'New' | 'Contacted' | 'Responded' | 'Call Booked' | 'Proposal' | 'Won' | 'Lost';
  interest: 'Hot' | 'Warm' | 'Cold' | 'Dead';
  lastContact: string;
  nextFollowUp: string;
  notes: string;
  email?: string;
  phone?: string;
}

export interface DailyProgress {
  date: string;
  morningTasks: boolean[];
  afternoonTasks: boolean[];
}

export interface InvoiceItem {
  id: string;
  description: string;
  quantity: number;
  price: number;
}

export interface Invoice {
  id: string;
  number: string;
  clientId: string;
  clientName: string;
  date: string;
  dueDate: string;
  items: InvoiceItem[];
  status: 'Draft' | 'Sent' | 'Paid' | 'Overdue';
  total: number;
}

export interface Transaction {
  id: string;
  date: string;
  description: string;
  amount: number;
  type: 'Income' | 'Expense';
  category: string;
}

export interface Reminder {
  id: string;
  text: string;
  datetime: string; // ISO string
  completed: boolean;
  triggeredIntervals: string[]; // List of interval IDs that have already alerted (e.g. '1h', '2h')
}

export interface IntegrationSubscription {
  id: string;
  provider: string;
  plan: string;
  cost: number;
  billingCycle: 'Monthly' | 'Quarterly' | 'Annual';
  renewalDate: string;
  status: 'Active' | 'Paused' | 'Canceled';
  seats?: number;
  notes?: string;
}

export interface ApiKeyEntry {
  id: string;
  label: string;
  provider: string;
  key: string;
  createdAt: string;
  lastUsed?: string;
  status: 'active' | 'disabled';
  notes?: string;
}

export interface ContentBasket {
  id: string;
  name: string;
  theme: string;
  description: string;
  cadencePerWeek: number;
  pillars: string[];
  prompts: string[];
}

export interface ContentPlanBasketSelection {
  basketId: string;
  frequencyPerWeek: number;
}

export interface ClientContentPlan {
  clientId: string;
  startDate: string;
  weeks: number;
  postingDays: string[]; // e.g. ['Mon','Thu']
  basketSelections: ContentPlanBasketSelection[];
}

export interface ImportResult {
  added: number;
  sections: number;
}

export type SaveStatus = 'idle' | 'saving' | 'saved' | 'error';

export interface DataContextType {
  // System Health
  saveStatus: SaveStatus;
  storageUsage: string; // MB
  forceRecovery: () => void;

  // Prospects
  prospects: Prospect[];
  addProspect: (prospect: Omit<Prospect, 'id'>) => void;
  updateProspect: (id: string, updates: Partial<Prospect>) => void;
  deleteProspect: (id: string) => void;
  deleteAllProspects: () => void;
  importProspects: (rawText: string) => ImportResult;
  
  // Clients
  clients: Client[];
  addClient: (client: Omit<Client, 'id'>) => Promise<void>;
  updateClient: (id: string, updates: Partial<Client>) => Promise<void>;
  deleteClient: (id: string) => Promise<void>;

  // Kanban
  kanbanItems: KanbanItem[];
  addKanbanItem: (item: Omit<KanbanItem, 'id'>) => void;
  updateKanbanItem: (id: string, updates: Partial<KanbanItem>) => void;
  deleteKanbanItem: (id: string) => void;

  // Calendar
  calendarEvents: CalendarEvent[];
  addCalendarEvent: (event: Omit<CalendarEvent, 'id'>) => Promise<CalendarEvent | undefined>;
  deleteCalendarEvent: (id: string) => void;

  // Daily Progress
  dailyProgress: Record<string, DailyProgress>;
  updateDailyTask: (date: string, block: 'morning' | 'afternoon', index: number) => void;
  
  // Content
  pageContent: Record<string, PageContent>;
  savePageContent: (content: PageContent) => void;
  savePageContentImmediate: (content: PageContent) => Promise<void>;

  // Client Portal Files
  clientFiles: UploadedFile[];
  addClientFile: (file: UploadedFile) => void;
  deleteClientFile: (id: string) => void;
  
  // Client Portal Folders
  clientFolders: ClientFolder[];
  addClientFolder: (folder: Omit<ClientFolder, 'id'>) => void;
  deleteClientFolder: (id: string) => void;
  folderOrders: Record<string, string[]>;
  updateFolderOrder: (clientId: string, path: string, order: string[]) => void;

  // Packages
  packages: PackageDefinition[];
  addPackage: (pkg: Omit<PackageDefinition, 'id'>) => Promise<PackageDefinition>;
  updatePackage: (id: string, updates: Partial<PackageDefinition>) => Promise<void>;
  deletePackage: (id: string) => Promise<void>;
  assignPackageToClient: (clientId: string, packageId: string, startDate: string) => Promise<void>;
  removePackageAssignment: (clientId: string, assignmentId: string) => Promise<void>;

  // Finance
  invoices: Invoice[];
  addInvoice: (invoice: Omit<Invoice, 'id'>) => void;
  updateInvoice: (id: string, updates: Partial<Invoice>) => void;
  deleteInvoice: (id: string) => void;

  transactions: Transaction[];
  addTransaction: (transaction: Omit<Transaction, 'id'>) => void;
  deleteTransaction: (id: string) => void;

  // Reminders (Blitz)
  reminders: Reminder[];
  addReminder: (reminder: Omit<Reminder, 'id' | 'completed' | 'triggeredIntervals'>) => void;
  deleteReminder: (id: string) => void;
  completeReminder: (id: string) => void;
  markReminderInterval: (id: string, intervalId: string) => void;

  // Integrations & API Keys
  subscriptions: IntegrationSubscription[];
  apiKeys: ApiKeyEntry[];
  addSubscription: (sub: Omit<IntegrationSubscription, 'id'>) => Promise<void>;
  updateSubscription: (id: string, updates: Partial<IntegrationSubscription>) => Promise<void>;
  deleteSubscription: (id: string) => Promise<void>;
  addApiKey: (entry: Omit<ApiKeyEntry, 'id' | 'createdAt'>) => Promise<void>;
  updateApiKey: (id: string, updates: Partial<ApiKeyEntry>) => Promise<void>;
  deleteApiKey: (id: string) => Promise<void>;

  // Content Planning
  contentPlans: Record<string, ClientContentPlan>;
  saveContentPlan: (plan: ClientContentPlan) => Promise<void>;
  deleteContentPlan: (clientId: string) => Promise<void>;
  
  // System
  exportData: () => string;
  importData: (json: string) => void;
  recoverLegacyData: () => void;
  hardReset: () => void;
}
